/**
 * SourceBadge
 * -----------
 * A small pill that indicates whether a fortune came from the AI or the
 * local seed pool (the offline fallback).
 *
 * Visual design:
 *   - AI    : indigo gradient + sparkle
 *   - Seed  : neutral stone + scroll icon
 *
 * Kept as its own component so both the cookie paper and the history
 * list render the same thing. Change it once, it updates everywhere.
 */
export default function SourceBadge({ source, size = "sm" }) {
  const isAi = source === "ai";
  const text = isAi ? "AI" : "Default";
  const icon = isAi ? "\u2728" : "\uD83D\uDCDC"; // ✨ or 📜
  const title = isAi
    ? "Generated by an AI language model"
    : "From the built-in seed collection (AI unavailable or disabled)";

  const sizeClasses = size === "xs" ? "text-[10px] px-1.5 py-0.5" : "text-xs px-2 py-0.5";
  const colorClasses = isAi
    ? "bg-gradient-to-r from-indigo-500 to-fuchsia-500 text-white"
    : "bg-stone-200 text-stone-700";

  return (
    <span
      title={title}
      className={`inline-flex items-center gap-1 rounded-full font-medium ${sizeClasses} ${colorClasses}`}
    >
      <span aria-hidden="true">{icon}</span>
      <span>{text}</span>
    </span>
  );
}
